In [1]:
import torch

In [2]:
x = torch.rand(5, 3)
x

tensor([[0.7804, 0.9211, 0.5716],
        [0.0266, 0.1582, 0.2237],
        [0.1517, 0.1782, 0.6200],
        [0.1475, 0.7855, 0.8113],
        [0.4616, 0.6214, 0.6662]])

In [3]:
x = torch.zeros(5, 3, dtype = torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [4]:
x = torch.tensor([5.3, 2])
print(x)

tensor([5.3000, 2.0000])


In [5]:
x.new_ones(5,2, dtype = torch.long)

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]])

In [6]:
y = x.view(2)

In [7]:
y

tensor([5.3000, 2.0000])

In [8]:
x = torch.ones(2, 2, requires_grad=True)

In [9]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [10]:
y = x + 2

In [11]:
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [12]:
z = y * y * 3
out = z.mean()

In [13]:
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


In [14]:
a = torch.randn(2, 2)
a = ((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [15]:
out.backward()

In [16]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [17]:
x = torch.randn(3, requires_grad = True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
    
print(y)

tensor([943.4638, 608.1461, 420.9791], grad_fn=<MulBackward0>)


In [18]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype = torch.float)
y.backward(gradients)
print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [19]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
