In [2]:
# from gensim.models import KeyedVectors
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from collections import defaultdict
from nltk.tokenize import RegexpTokenizer

In [2]:
indices = [0, 5, 6]
train = []
tokenizer = RegexpTokenizer(r'\w+')

for line in open("../snli_1.0/snli_1.0_test.txt"):
    entry = line.split("\t")
    label, sentence1, sentence2 = [entry[i] for i in indices]
    sentence1 = tokenizer.tokenize(sentence1.lower())
    sentence2 = tokenizer.tokenize(sentence2.lower())
    train.append((sentence1, sentence2, label))

In [3]:
for entry in train[1:3]:
    s1, s2, l = entry
    print("sentence1: {}, sentence2: {}, label: {} END".format(s1, s2, l))

sentence1: ['this', 'church', 'choir', 'sings', 'to', 'the', 'masses', 'as', 'they', 'sing', 'joyous', 'songs', 'from', 'the', 'book', 'at', 'a', 'church'], sentence2: ['the', 'church', 'has', 'cracks', 'in', 'the', 'ceiling'], label: neutral END
sentence1: ['this', 'church', 'choir', 'sings', 'to', 'the', 'masses', 'as', 'they', 'sing', 'joyous', 'songs', 'from', 'the', 'book', 'at', 'a', 'church'], sentence2: ['the', 'church', 'is', 'filled', 'with', 'song'], label: entailment END


In [194]:
w2i = defaultdict(lambda: len(w2i))
l2i = defaultdict(lambda: len(l2i))
UNK = w2i["<unk>"]

In [5]:
w2i["test"]

1

In [174]:
w2i

defaultdict(<function __main__.<lambda>>, {'<unk>': 0})

In [6]:
x = torch.Tensor(torch.rand(3, 4))
softmax = nn.Softmax(dim = 1)

In [13]:
sims

tensor([0.5000, 0.3000, 0.8000])

In [12]:
sims = torch.Tensor([0.5, 0.3, 0.8])

In [8]:
weighted = torch.sum(torch.t(torch.t(x) * sims), dim = 0)

In [9]:
np.dot(sims, x)

array([0.7834704, 1.0361758, 0.9726609, 0.6262558], dtype=float32)

In [114]:
torch.mv(torch.t(x), sims)

tensor([0.7544, 0.7832, 0.4038, 0.6040])

In [115]:
torch.t(torch.t(x) * sims)

tensor([[0.1078, 0.1436, 0.0600, 0.1803],
        [0.1393, 0.1145, 0.1772, 0.1967],
        [0.5072, 0.5252, 0.1667, 0.2270]])

In [135]:
sims = torch.Tensor([[0.5, 0.3, 0.8], [0.2, 0.7, 0.4])

In [136]:
softmax(sims)

tensor([[0.3156, 0.2584, 0.4260],
        [0.2584, 0.4260, 0.3156]])

In [129]:
torch.matmul(sims, x)

tensor([[0.7544, 0.7832, 0.4038, 0.6040],
        [0.6218, 0.5871, 0.5207, 0.6445]])

In [35]:
def get_align(sims, embeddings):
    assert(sims.size()[1] == embeddings.size()[0])
    softmax = nn.Softmax(dim = 1)
    sims = softmax(sims)
    reweighted = torch.matmul(sims, embeddings)
    return(reweighted)

In [199]:
get_align(sims, x)

tensor([[0.4582, 0.4689, 0.2792, 0.4041],
        [0.4537, 0.4439, 0.3483, 0.4620]])

## Example
First sentence = "Hey how are you?"

Second sentence = "hey there!"

In [57]:
glove = KeyedVectors.load_word2vec_format("../pretrained_vectors/glove_50_word2vec.txt")

In [64]:
glove_tensor = torch.FloatTensor(glove.vectors)

In [67]:
emb = nn.Embedding.from_pretrained(glove_tensor)

In [195]:
def read_test_data(file):
    with open(file) as f:
        for line in f:
            words = line.strip()
            yield([w2i[x] for x in words.split(" ")])

example_train = [list(read_test_data("test_sentences.txt"))]

In [210]:
pretrained_glove = np.random.uniform(-.25, .25, (len(w2i), 50))
print(len(pretrained_glove))
pretrained_glove[0] = 0
print(len(pretrained_glove))

7
7


In [213]:
for key in glove.vocab.keys():
    if key in w2i:
        print("key: {}".format(w2i[key]))
        pretrained_glove[w2i[key]] = glove[key]
    else:
        continue

key: 6
key: 3
key: 5
key: 4
key: 2
key: 1


In [214]:
pretrained_glove

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [-7.00

In [3]:
# fake embedding for first sentence: 4 words 6 dims
first = torch.rand(4, 6)

# fake embedding for second sentence: 2 words 6 dims
second = torch.rand(2, 6)

In [4]:
linear_f = nn.Linear(in_features=6, out_features=7)

In [5]:
# transformed1 = linear_f(first)
# transformed2 = linear_f(second)
transformed1, transformed2 = [linear_f(x) for x in [first, second]]

In [7]:
transformed2

tensor([[ 0.3529, -0.4868,  0.1069, -0.0204, -0.4639, -0.2611,  0.0079],
        [ 0.2474, -0.2837,  0.0292,  0.0028, -0.3747, -0.1736, -0.2402]],
       grad_fn=<AddmmBackward>)

In [8]:
aligned1 = torch.bmm(transformed1, torch.t(transformed2))
aligned2 = torch.bmm(transformed2, torch.t(transformed1))

RuntimeError: Expected 3-dimensional tensor, but got 2-dimensional tensor for argument #1 'batch1' (while checking arguments for bmm)

In [33]:
torch.mm(transformed1[[1]], torch.t(transformed2))

tensor([[1.9375, 1.4376]], grad_fn=<MmBackward>)

In [190]:
first

tensor([[0.6133, 0.5491, 0.3429, 0.6659, 0.3139, 0.0492],
        [0.0329, 0.5614, 0.8330, 0.9532, 0.2683, 0.4912],
        [0.0598, 0.3936, 0.6898, 0.8176, 0.7837, 0.0418],
        [0.8536, 0.0942, 0.2509, 0.8126, 0.1934, 0.2965]])

In [38]:
## w_hat_a = get_align(aligned2, first) <- gets concatenated with sentence_b's embeddings
get_align(aligned2, first)

## w_hat_b = get_align(aligned1, second) <- gets concatenated with sentence_a's embeddings.

tensor([[0.7394, 0.7154, 0.3504, 0.7228, 0.4922, 0.4864],
        [0.7376, 0.7225, 0.3476, 0.7094, 0.4772, 0.4806]],
       grad_fn=<MmBackward>)

In [39]:
concatenated2 = torch.cat((second, get_align(aligned2, first)), 1)

In [40]:
concatenated1 = torch.cat((first, get_align(aligned1, second)),1)

In [41]:
## second layer
linear_pair = nn.Linear(in_features = 2*6, out_features = 7)
paired1 = linear_pair(concatenated1)
paired2 = linear_pair(concatenated2)

In [42]:
paired1

tensor([[ 0.2812, -0.4679,  0.4616,  0.4147,  0.4096,  0.4283,  0.3498],
        [ 0.4729, -0.5461,  0.5470,  0.2918,  0.3802,  0.5535,  0.5348],
        [ 0.2250, -0.4903,  0.4564,  0.4962,  0.4911,  0.3095,  0.2507],
        [ 0.1051, -0.3377,  0.4247,  0.4454,  0.3986,  0.3006,  0.3460]],
       grad_fn=<AddmmBackward>)

In [45]:
v1 = torch.sum(paired1, 0)
v2 = torch.sum(paired2, 0)

In [48]:
torch.cat((v1, v2))

tensor([ 1.0841, -1.8420,  1.8897,  1.6481,  1.6795,  1.5918,  1.4813,  0.6895,
        -0.5484,  0.9582,  0.7871,  1.1696,  0.8275,  1.0047],
       grad_fn=<CatBackward>)

In [228]:
softmax(relu(paired1))

tensor([[0.1063, 0.0954, 0.1622, 0.0888, 0.0888, 0.0915, 0.1008, 0.0888, 0.0888,
         0.0888],
        [0.1125, 0.0889, 0.1595, 0.1058, 0.0889, 0.0889, 0.0889, 0.0889, 0.0889,
         0.0889],
        [0.1194, 0.0868, 0.1669, 0.0868, 0.0868, 0.0868, 0.1064, 0.0868, 0.0868,
         0.0868],
        [0.0939, 0.1021, 0.1605, 0.0992, 0.0885, 0.0885, 0.1020, 0.0885, 0.0885,
         0.0885]], grad_fn=<SoftmaxBackward>)

In [159]:
class MLP(nn.Module):
    def __init__(self, **kwargs):
        '''
        PARAMS:
        sent1 : tensor for sentence1
        sent2 : tensor for sentence2
        hidden_size : number of units in the hidden layer, 200 in the paper
        output_size : number of units in the final layer (decision), 3 for entailment
        emb_size : embedding size, 300 (might use glove instead to test)
        
        LAYERS:
        linear_t : transformation layer (first layer in the network)
        linear_p : paired layer which uses original word embeddings and their concatenation with the attended vectors
        linead_d : decision layer which uses final concatenation of representations of sentences and decides if they
                   entail or contradict each other or are neutral.
        '''
        super(MLP, self).__init__()
        self.hidden_size = kwargs["HIDDEN_SIZE"]
        self.output_size = kwargs["OUTPUT_SIZE"]
        self.emb_size = kwargs["EMB_SIZE"]
        self.nwords = kwargs["SENT_LEN"]
        
        self.embedding = nn.Embedding(self.nwords, self.emb_size)
        self.linear_t = nn.Sequential(nn.Linear(self.emb_size, self.hidden_size), nn.ReLU(), nn.Linear(self.hidden_size, self.hidden_size))
        self.linear_p = nn.Sequential(nn.Linear(self.emb_size*2, self.hidden_size), nn.ReLU(), nn.Linear(self.hidden_size, self.hidden_size))
        self.linear_d = nn.Sequential(nn.Linear(self.emb_size*2, self.hidden_size), nn.ReLU(), nn.Linear(self.hidden_size, self.output_size), nn.Softmax())
    
#     def get_align(self, )
    def forward(self, sentence1, sentence2):
        sent1 = self.embedding(sentence1)
        sent2 = self.embedding(sentence2)
        
        

In [216]:
model = MLP(EMB_SIZE = 50, HIDDEN_SIZE = 100, OUTPUT_SIZE = 3, SENT_LEN = 7)
model.embedding.weight.data.copy_(torch.from_numpy(pretrained_glove))
model.embedding.weight.requires_grad = False

In [218]:
model(torch.LongTensor([6,6]), torch.LongTensor([1,5]))

In [166]:
example_train

[[[1, 2, 3, 4], [1, 5], [6, 6]]]